export const rawQuestions = [
  {
    Question: "What is your Human Capital management platform? (select all that apply)",
    "Radar Category": "",
    "Page Title": "HR Ecosystem Maturity",
    Response: "Select all that apply",
    BASIC: "- Workday\n- SAP SuccessFactors\n- Oracle\n- UKG\n- ADP\n- Other (please type in)",
    EMERGING: "",
    MATURE: "",
    LEADER: "",
    "Type of field": "Check box Multi-Select (no limit)",
    "Error message": "Please select at least one value",
    Num: 1,
  },
  {
    Question: "How would you describe the maturity levels of your HR technology ecosystem?",
    "Radar Category": "HR Ecosystem Maturity",
    "Page Title": "HR Ecosystem Maturity",
    Response: "See 4 levels options",
    BASIC: "Manual processes, isolated systems, minimal analytics, not aligned with strategy.",
    EMERGING: "Some automation, partial system integration, basic analytics, initial alignment.",
    MATURE: "Mostly automated, good integration, regular analytics, aligned with strategy.",
    LEADER: "Fully integrated, advanced analytics and AI, real-time insights, fully strategic.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: "How would you describe the maturity levels of your HR technology ecosystem?",
  },
  {
    Question: "How would you rate the integration and use of skills in your HR processes and technology?",
    "Radar Category": "Skills Maturity",
    "Page Title": "Skills Maturity",
    Response: "See 4 levels options",
    BASIC: "Minimal skill integration; tech lacks tools for tracking or developing skills; low visibility.",
    EMERGING: "Some skill consideration; limited tech features; occasional skill gap identification.",
    MATURE: "Skills integrated into key processes; robust tech features; proactive gap management.",
    LEADER: "Skills are a core focus; advanced tech and AI used; real-time data drives decisions.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: "How would you rate the integration and use of skills in your HR processes and technology?",
  },
  {
    Question: "What are the near term top 3 strategic talent priorities for your organization?",
    "Radar Category": "",
    "Page Title": "HR Strategy and Planning",
    Response: "Select your organization 3 priorities",
    BASIC:
      "- Become a skills based organization\n- Workforce planning & intelligence (use AI and market insights to drive talent & business plans)\n- Talent acquisition & retention (develop robust strategies to attract mixed talents from permanent workers to contractors and gigs etc.)\n- Diversity, Equity and Inclusion\n- Upskilling and reskilling (invest in learning and development programs to prepare employees for future roles)\n- Employee Sentiment, Experience and Engagement\n- Agile Talent Management (Career Pathing, Succession, Performance Management, Learning Management)\n- Data-Driven HR Decision Making\n- Employer Value Proposition\n- Adapting to technological advancements (integrate Artificial intelligence, Machine Learning into HR processes)",
    EMERGING: "",
    MATURE: "",
    LEADER: "",
    "Type of field": "Check box Multi-Select (max 3 values)",
    "Error message": "Please select 3 priorities",
    Num: 4,
  },
  {
    Question: "What is your organization readiness for these priorities?",
    "Radar Category": "HR Strategy and Planning",
    "Page Title": "HR Strategy and Planning",
    Response: "See 4 levels options",
    BASIC: "Some tools exist but lack standardization; basic metrics; starting alignment.",
    EMERGING: "Standardized strategies; clear alignment; systematic metrics; cross-functional support.",
    MATURE: "Data-driven execution; continuous monitoring; aligned goals; high engagement.",
    LEADER: "Strategy embedded in culture; innovation; predictive analytics; strong agility.",
    "Type of field": "Slider Field",
    "Error message": "Slider Field",
    Num: 5,
  },
  {
    Question: "How widely are the above HR technologies adopted and utilized by HR and business teams?",
    "Radar Category": "Implementation and Change Management",
    "Page Title": "Implementation and Change Management",
    Response: "See 4 levels options",
    BASIC: "Awareness and occasional use of HR technologies, minimal standardization, limited use, early benefits.",
    EMERGING: "Comprehensive HR Technology solution implemented, standardized processes, regular use, improved integration.",
    MATURE: "Advanced tech fully integrated, strong data use, high adoption, strategic alignment.",
    LEADER: "HR Technologies embedded in culture, continuous innovation and optimization, real-time analytics, full business impact.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: 6,
  },
  {
    Question: "What is the level of adoption by HR & business for the above HR Technologies?",
    "Radar Category": "Implementation and Change Management",
    "Page Title": "Implementation and Change Management",
    Response: "See 4 levels options",
    BASIC:
      "HR:\n- HR technologies are implemented for specific functions (e.g., payroll, basic recruitment).\n- Some degree of process standardization is achieved.\n- Initial training provided to HR staff.\n- Data is collected but not extensively analyzed.\n\nBusiness:\n- Awareness and occasional use of HR technologies outside HR.\n- Limited integration with broader business systems (e.g., finance, operations).\n- Early-stage benefits realized in HR-specific areas.",
    EMERGING:
      "HR:\n- Comprehensive HR technology solutions are implemented (e.g., ATS, LMS, performance management systems).\n- Processes are standardized and consistently followed.\n- Regular training programs for HR staff and end-users.\n- Data-driven decision-making begins to inform HR practices.\n\nBusiness:\n- Broader business begins to see the impact of HR technologies on overall efficiency and effectiveness.\n- Integration with other business systems improves. - Collaboration between HR and other departments to leverage technology for better outcomes.",
    MATURE:
      "HR:\n- Advanced HR technologies are fully integrated into all HR functions (e.g., AI-driven recruitment, predictive analytics for talent management).\n- Strong emphasis on data analytics and continuous improvement.\n- High level of user adoption and competency across HR and related functions.\n- Strategic alignment with business goals.\n\nBusiness:\n- Significant impact of HR technologies on overall business performance.\n- High integration with other business functions, enabling seamless workflows.\n- Enhanced collaboration and data sharing between HR and other departments.\n- Improved employee experience and productivity.",
    LEADER:
      "HR:\n- HR technologies are deeply embedded in organizational culture and daily operations.\n- Continuous optimization and innovation using advanced technologies (e.g., machine learning, blockchain).\n- Comprehensive, real-time analytics inform strategic and operational decisions.\n- High level of agility and responsiveness to changes in the business environment.\n\nBusiness:\n- HR technologies drive sustained competitive advantage and business transformation.\n- Full integration with all business functions, enabling a holistic approach to talent management.\n- Data from HR technologies informs strategic business initiatives and fosters innovation.\n- High employee engagement and satisfaction due to seamless and efficient HR processes.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: 7,
  },
  {
    Question:
      "From the below listed HR Technologies, which ones your organization consider to implement, improve or change for enhancing your skills management capabilities? (select all that apply)",
    "Radar Category": "",
    "Page Title": "Implementation and Change Management",
    Response: "Select all that apply",
    BASIC:
      "- Workforce planning & intelligence\n- Talent Marketplace\n- Career Pathing\n- Mentoring\n- Succession Planning\n- Internal Mobility\n- Contractor Management System\n- Candidate Relationship Management (CRM)\n- Applicant Tracking System (ATS)\n- Job Boards\n- Interview Scheduling\n- Interview Intelligence\n- Chatbot\n- Onboarding platform\n- Offboarding platform\n- Learning Management System\n- Learning Experience Platforms\n- Performance Management System\n- Alumni",
    EMERGING: "",
    MATURE: "",
    LEADER: "",
    "Type of field": "Check box Multi-Select (no limit)",
    "Error message": "Please select at least one value",
    Num: 8,
  },
  {
    Question: "How would you rate your organization's capability to implement and manage these HR processes and technologies?",
    "Radar Category": "Implementation and Change Management",
    "Page Title": "Implementation and Change Management",
    Response: "See 4 levels options",
    BASIC: "Limited internal resources and expertise; significant external support needed.",
    EMERGING: "Mix of internal resources and external support; some technologies managed internally.",
    MATURE: "Strong internal expertise; minimal external support needed for specialized tasks.",
    LEADER: "Robust internal resources; capable of independent implementation and management.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: 9,
  },
  {
    Question: "Is your organization currently leveraging artificial intelligence (AI) in its operations?",
    "Radar Category": "Digital HR Transformation",
    "Page Title": "Artificial Intelligence",
    Response: "See 4 levels options",
    BASIC: "AI is used in some pilot projects or isolated cases without major integration.",
    EMERGING: "AI is systematically applied in several areas, with a structured integration approach.",
    MATURE: "AI is widely integrated into many processes; frameworks and governance are established.",
    LEADER: "AI is deeply embedded in culture and operations, driving innovation and agility.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: 10,
  },
  {
    Question: "How would you assess the maturity of the digital experience offered by your HR ecosystem?",
    "Radar Category": "Digital HR Transformation",
    "Page Title": "Digital Experience",
    Response: "See 4 levels options",
    BASIC: "HR systems are siloed, with no data sharing or integration; manual data entry is common.",
    EMERGING: "Some systems are connected with limited data sharing; integration is basic and partly manual.",
    MATURE: "Most systems are integrated with automated data exchange; reliable data consistency.",
    LEADER: "All systems are fully integrated; real-time data updates and high data accuracy.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: 11,
  },
  {
    Question: "How do you assess the effectiveness of data utilization in HR decision-making within your organization?",
    "Radar Category": "Digital HR Transformation",
    "Page Title": "HR Data",
    Response: "See 4 levels options",
    BASIC: "Limited data collection; data rarely informs HR strategies or decisions.",
    EMERGING: "Some decisions use basic data; data collected but not deeply analyzed.",
    MATURE: "Most decisions are data-supported; systematic data collection and analysis.",
    LEADER: "Data-driven decisions fully embedded; advanced analytics and predictive modeling widely used.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: 12,
  },
  {
    Question: "Please assess the maturity of your Workforce Planning System.",
    "Radar Category": "",
    "Page Title": "Workforce Planning System",
    Response: "See 4 levels options",
    BASIC: "Reactive planning; manual processes; limited workforce intelligence; no strategic alignment.",
    EMERGING: "Some automation; basic forecasting tools; limited integration; short-term planning with some data insights.",
    MATURE: "Automated, integrated processes; regular use of analytics and workforce intelligence; medium to long-term strategic planning.",
    LEADER:
      "Fully integrated systems; advanced analytics and predictive modeling; comprehensive, data-driven workforce planning and intelligence aligned with business goals.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: 13,
  },
  {
    Question: "What is your Workforce Planning System? (select all that apply)",
    "Radar Category": "",
    "Page Title": "Workforce Planning System",
    Response: "Workday Adaptive Planning",
    BASIC:
      "- Workday Adaptive Planning\n- SAP SuccessFactors\n- Oracle HCM\n- Eightfold\n- 365 Talents\n- Visier\n- Nakisa\n- Agentnoon\n- TalentNeuron\n- Lightcast\n- Other (please type in)\n- I don't know\n- Not implemented",
    EMERGING: "",
    MATURE: "",
    LEADER: "",
    "Type of field": "Check box Multi-Select (no limit)",
    "Error message": "Please select at least one value",
    Num: 14,
  },
  {
    Question: "Please evaluate the maturity of your Vendor Management System (Contingent Worker)",
    "Radar Category": "",
    "Page Title": "Extended Workforce",
    Response: "See 4 levels options",
    BASIC: "Limited or no VMS usage; manual management with spreadsheets and emails; low visibility.",
    EMERGING: "Basic VMS functionality; some automation; limited integration; basic reporting and tracking.",
    MATURE: "Extensive VMS use; automation of most tasks; integrated systems; advanced reporting and analytics.",
    LEADER: "Fully integrated VMS; end-to-end automation; AI-driven analytics; real-time insights for strategic decisions.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: 15,
  },
  {
    Question: "What is your Vendor Management System? (select all that apply)",
    "Radar Category": "",
    "Page Title": "Extended Workforce",
    Response: "Workday VNDLY",
    BASIC:
      "- Workday VNDLY\n- SAP Fieldglass\n- Oracle Peoplesoft VMS\n- Beeline\n- Coupa\n- iValua\n- Bluesky\n- Flextrack\n- Skillstream\n- Renhead\n- Other (please type in)\n- I don't know\n- Not implemented",
    EMERGING: "",
    MATURE: "",
    LEADER: "",
    "Type of field": "Check box Multi-Select (no limit)",
    "Error message": "Please select at least one value",
    Num: 16,
  },
  {
    Question: "Please assess the maturity of your Talent Acquisition Systems (CRM, ATS, Career Sites etc.)",
    "Radar Category": "",
    "Page Title": "Talent Acquisition System",
    Response: "See 4 levels options",
    BASIC: "Manual processes; limited technology; basic candidate tracking; no skills management.",
    EMERGING: "Partial tech use (e.g., ATS for resume collection, basic CRM); some automation; limited skills tracking.",
    MATURE: "Most processes automated (e.g., ATS, CRM); integrated skills management; use of data analytics for decision making.",
    LEADER:
      "Fully automated and integrated systems; advanced AI for skills and talent matching; comprehensive CRM; highly efficient, strategic recruitment processes.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: 17,
  },
  {
    Question: "Which systems are used for Talent Acquisition? (select all that apply)",
    "Radar Category": "",
    "Page Title": "Talent Acquisition System",
    Response: "Phenom",
    BASIC:
      "- Workday\n- SAP SuccessFactors\n- Oracle HCM\n- Phenom\n- Eightfold\n- iCims\n- Avature\n- SmartRecruiters\n- Beamery\n- Cornerstone\n- Other (please type in)\n- I don't know\n- Not implemented",
    EMERGING: "",
    MATURE: "",
    LEADER: "",
    "Type of field": "Check box Multi-Select (no limit)",
    "Error message": "Please select at least one value",
    Num: 18,
  },
  {
    Question:
      "Please assess the maturity of your Talent Management Systems (Career Pathing, Mentoring, Talent marketplace, Internal Mobility, Gigs etc.)",
    "Radar Category": "",
    "Page Title": "Talent Management System",
    Response: "See 4 levels options",
    BASIC: "Manual and disconnected processes; minimal tech use; managed with spreadsheets; no strategic alignment; limited skills management.",
    EMERGING:
      "Some automation (e.g., online reviews); partial HRIS integration; standardized processes; limited reskilling, and skills tracking; not fully connected to business strategy.",
    MATURE:
      "Automated and integrated systems (e.g., LMS, succession planning); regular data analytics use; active reskilling, and skills management; aligned with business strategy.",
    LEADER:
      "Fully integrated systems; seamless data flow; advanced predictive modeling; strong focus on reskilling, and skills management; deeply embedded in business strategy.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: 19,
  },
  {
    Question: "Which systems are used for Talent Management? (select all that apply)",
    "Radar Category": "",
    "Page Title": "Talent Management System",
    Response: "Gloat",
    BASIC:
      "- Workday\n- SAP SuccessFactors\n- Oracle HCM\n- Phenom\n- Eightfold\n- Gloat\n- Fuel50\n- Career Spark\n- PyMetrics\n- Reejig\n- Other (please type in)\n- I don't know\n- Not implemented",
    EMERGING: "",
    MATURE: "",
    LEADER: "",
    "Type of field": "Check box Multi-Select (no limit)",
    "Error message": "Please select at least one value",
    Num: 20,
  },
  {
    Question:
      "Please assess the maturity of your Learning & Development Systems (Learning Managament Systems, Digital Learning, Succsession Planning etc.).",
    "Radar Category": "",
    "Page Title": "Learning & Development System",
    Response: "See 4 levels options",
    BASIC: "Manual L&D processes; ad-hoc learning programs; minimal tech; limited skills focus; not aligned with business.",
    EMERGING:
      "Some automation (e.g., basic e-learning); limited HRIS integration; standardized learning programs; basic reskilling and skills management.",
    MATURE: "Automated, integrated L&D systems; analytics for tracking; active reskilling and skills management; aligned with business needs.",
    LEADER:
      "Fully integrated systems; advanced analytics; personalized learning; strong focus on reskilling and skills management; deeply strategic and continuously improving.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: 21,
  },
  {
    Question: "Which systems are used for Learning & Development? (select all that apply)",
    "Radar Category": "",
    "Page Title": "Learning & Development System",
    Response: "Docebo",
    BASIC:
      "- Workday\n- SAP SuccessFactors\n- Oracle HCM\n- Cornerstone\n- 360Learning\n- Docebo\n- HealthStream\n- Moodle\n- Bridge\n- SmarterU\n- Other (please type in)\n- I don't know\n- Not implemented",
    EMERGING: "",
    MATURE: "",
    LEADER: "",
    "Type of field": "Check box Multi-Select (no limit)",
    "Error message": "Please select at least one value",
    Num: 22,
  },
  {
    Question: "Please assess the maturity of your Performance Management Systems.",
    "Radar Category": "",
    "Page Title": "Performance Management System",
    Response: "See 4 levels options",
    BASIC: "Manual processes; limited tech use; infrequent reviews; no reskilling or skills focus; not aligned with business goals.",
    EMERGING:
      "Some automation (e.g., online performance reviews); limited HRIS integration; regular but generic feedback; initial reskilling and skills management efforts; partial alignment with business goals.",
    MATURE:
      "Automated, integrated systems; analytics use; structured reviews; active reskilling and skills management; strong alignment with business objectives.",
    LEADER:
      "Fully integrated systems; advanced predictive modeling; continuous feedback; comprehensive reskilling and skills management; deeply embedded in strategy, driving continuous improvement and impact.",
    "Type of field": "Slider Field",
    "Error message": "Your desired level cannot be smaller than the current level.",
    Num: 23,
  },
  {
    Question: "What is your Performance Management System? (select all that apply)",
    "Radar Category": "",
    "Page Title": "Performance Management System",
    Response: "SAP SuccessFactors",
    BASIC:
      "- Workday\n- SAP SuccessFactors\n- Oracle HCM\n- Cornerstone\n- CultureAmp\n- Leapsome\n- Lattice\n- Trakstar\n- Reflektive\n- Weekly10\n- Other (please type in)\n- I don't know\n- Not implemented",
    EMERGING: "",
    MATURE: "",
    LEADER: "",
    "Type of field": "Check box Multi-Select (no limit)",
    "Error message": "Please select at least one value",
    Num: 24,
  },
];
