const categoriesList = [
  {
    DiamondLoc: "topLeft",
    Type: "Leadership & Change",
    description:
      "Encourage, inspire, and motivate employees to exceed expectations, create positive change, and enhance personal and professional growth.",
  },
  {
    DiamondLoc: "topRight",
    Type: "Extended Workforce",
    description:
      "Leverage diverse skills and expertise, optimize costs and performance, and foster innovation and collaboration across internal and external stakeholders.",
  },
  {
    DiamondLoc: "rightCircle",
    Type: "Workforce Planning",
    description:
      "Forecast workforce supply and demand, assess gaps, and determine target talent management interventions to fulfill your mandate and strategic objectives.",
  },
  {
    DiamondLoc: "bottomCircle",
    Type: "Workforce Productivity",
    description: "Identify methods to improve the efficiency, effectiveness, and quality of your work processes and outcomes.",
  },
  {
    DiamondLoc: "leftCircle",
    Type: "Talent Acquisition",
    description:
      "Find, identify, and select qualified candidates for open positions. Refine key elements of the employee journey to drive organizational success.",
  },
  {
    DiamondLoc: "middleCircle",
    Type: "Talent Management",
    description:
      "Attract and retain talent in the long term. Identify development opportunities and strategies that motivate teams to be at their best performance.",
  },
];

const questionBank = [
  {
    Description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    DiamondLoc: "topLeft",
    Type: "Leadership & Change",
    Current: 0,
    Desired: 0,
    Number: "1",
    Of: "9",
    Dimension: "Holistic approach to Transformation ",
    Response_1: "Our transformation projects are very ad hoc, and the business is not enagged or listened to.",
    Response_2: "My answer lies between 1 and 3",
    Response_3:
      "We are making progress, and while we attempt to listen to the business, it's not always clear which problems our  technology is solving.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our approach to transformation prioritizes understanding business problems using techniques such as design thinking to redesign experiences before implementing technology solutions.",
  },
  {
    DiamondLoc: "topLeft",
    Type: "Leadership & Change",
    Current: 0,
    Desired: 0,
    Number: "2",
    Of: "9",
    Dimension: "Scientific Data Driven",
    Response_1: "Our innovation strategy lacks reliable data and modern tools and have no standard way of executing innovation.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Although we sporadically use data and toolsets, our problem-solving approach lacks consistency and a true scientific approach. ",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "We invest heavily in data, toolsets, training, and research to drive innovation using advanced technology.",
  },
  {
    DiamondLoc: "topLeft",
    Type: "Leadership & Change",
    Current: 0,
    Desired: 0,
    Number: "3",
    Of: "9",
    Dimension: "Experimental",
    Response_1:
      "We are not encouraged to think creatively, as we are expected to adhere to our existing business model without much emphasis on innovation for new models.",
    Response_2: "My answer lies between 1 and 4",
    Response_3: "While we talk about the importance of innovation, we are not encouraged to take risks, and fear of failure holds us back.",
    Response_4: "My answer lies between 3 and 6",
    Response_5:
      "Our culture values experimentation and calculated risk-taking, supported by adherence to company wide methodologies. We have demonstrated success in generating new sources of growth.",
  },
  {
    DiamondLoc: "topLeft",
    Type: "Leadership & Change",
    Current: 0,
    Desired: 0,
    Number: "4",
    Of: "9",
    Dimension: "Transfromational Leadership",
    Response_1: "Leaders prioritize results and current models, but neglect innovation despite recognizing its importance.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Leaders prioritize short-term results over innovation, lacking a clear plan or resources to foster it.",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "Leadership drives innovation with strategic planning, adaptability, and guidance.",
  },
  {
    DiamondLoc: "topLeft",
    Type: "Leadership & Change",
    Current: 0,
    Desired: 0,
    Number: "5",
    Of: "9",
    Dimension: "Systemic Model for Change",
    Response_1: "My leaders don't prioritize fostering and monitoring change, leaving it mainly to HR.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Executives discuss change at a high level, but specialists handle it. No systemic approach to change exists.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our leaders prioritize change and foster organizational learning through openness and trust.  Busines leadership is synonymous with change leadership.",
  },
  {
    DiamondLoc: "topLeft",
    Type: "Leadership & Change",
    Current: 0,
    Desired: 0,
    Number: "6",
    Of: "9",
    Dimension: "Resourcing for Innovation",
    Response_1: "The organization does not devote resources to innovation and new business models.",
    Response_2: "My answer lies between 1 and 3",
    Response_3:
      "While we dedicate some resources to foster innovation we hinder innovation initiatives due to a lack of necessary skills and underfunding.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our organization prioritizes resource allocation and consistently reviews talent and resource allocation to align with high-impact areas. Leadership understands the quality and types of resources needed for success.",
  },
  {
    DiamondLoc: "topLeft",
    Type: "Leadership & Change",
    Current: 0,
    Desired: 0,
    Number: "7",
    Of: "9",
    Dimension: "Organizing Agility ",
    Response_1: "We are a rigid hierarchy model and functional siloes. Leadership lacks a clear strategy for increasing business agility.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "We're reorganizing from silos to cross-functional teams, but progress is limited.",
    Response_4: "My answer lies between 3 and 6",
    Response_5:
      "Our focus is on agility and scalability through a network of project teams. Our leadership successfully reorganized functional silos into integrated, cross-functional teams aligned to products or platforms in IT, R&D, product development, and engineering.",
  },
  {
    DiamondLoc: "topLeft",
    Type: "Leadership & Change",
    Current: 0,
    Desired: 0,
    Number: "8",
    Of: "9",
    Dimension: "Rewarding  Innovation",
    Response_1: "Innovation is not regarded as a core or legitimate career in our company and a pathway for senior management.",
    Response_2: "My answer lies between 1 and 3",
    Response_3:
      "While there are exceptions, most top talents are hesitant to pursue innovation and transformation jobs due to uncertainty about the career path and where it may lead.",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "We promote innovation and reward success at all levels. Transformative careers lead to senior leadership.",
  },
  {
    Description: "Nulla ipsum, deleniti totam rerum maxime explicabo iure quia magni modi voluptas nobis numquam.",
    DiamondLoc: "topLeft",
    Type: "Leadership & Change",
    Current: 0,
    Desired: 0,
    Number: "9",
    Of: "9",
    Dimension: "Sound Foundations",
    Response_1:
      "Outdated technology infrastructure hinders digital innovation. IT department creates ad hoc solutions due to insufficient investment.",
    Response_2: "My answer lies between 1 and 3",
    Response_3:
      "Our technology foundation is undergoing a transition with both strengths and weaknesses, leading to an inconsistent user experience. Investment efforts are underway, but the overall direction is not always clear.",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "Our technology foundation drives digital innovation with intuitive platforms, visible priorities, and clear communication.",
  },
  {
    Description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    DiamondLoc: "topRight",
    Type: "Extended Workforce",
    Current: 0,
    Desired: 0,
    Number: "1",
    Of: "5",
    Dimension: "Strategy & Leadership",
    Response_1: "Our transformation projects are very ad hoc, and the business is not enagged or listened to.",
    Response_2: "My answer lies between 1 and 3",
    Response_3:
      "We are making progress, and while we attempt to listen to the business, it's not always clear which problems our  technology is solving.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our approach to transformation prioritizes understanding business problems using techniques such as design thinking to redesign experiences before implementing technology solutions.",
  },
  {
    DiamondLoc: "topRight",
    Type: "Extended Workforce",
    Current: 0,
    Desired: 0,
    Number: "2",
    Of: "5",
    Dimension: "Service | Program Design",
    Response_1: "Our innovation strategy lacks reliable data and modern tools and have no standard way of executing innovation.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Although we sporadically use data and toolsets, our problem-solving approach lacks consistency and a true scientific approach. ",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "We invest heavily in data, toolsets, training, and research to drive innovation using advanced technology.",
  },
  {
    DiamondLoc: "topRight",
    Type: "Extended Workforce",
    Current: 0,
    Desired: 0,
    Number: "3",
    Of: "5",
    Dimension: "Process",
    Response_1:
      "We are not encouraged to think creatively, as we are expected to adhere to our existing business model without much emphasis on innovation for new models.",
    Response_2: "My answer lies between 1 and 4",
    Response_3: "While we talk about the importance of innovation, we are not encouraged to take risks, and fear of failure holds us back.",
    Response_4: "My answer lies between 3 and 6",
    Response_5:
      "Our culture values experimentation and calculated risk-taking, supported by adherence to company wide methodologies. We have demonstrated success in generating new sources of growth.",
  },
  {
    DiamondLoc: "topRight",
    Type: "Extended Workforce",
    Current: 0,
    Desired: 0,
    Number: "4",
    Of: "5",
    Dimension: "Technology",
    Response_1: "Leaders prioritize results and current models, but neglect innovation despite recognizing its importance.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Leaders prioritize short-term results over innovation, lacking a clear plan or resources to foster it.",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "Leadership drives innovation with strategic planning, adaptability, and guidance.",
  },
  {
    DiamondLoc: "topRight",
    Type: "Extended Workforce",
    Current: 0,
    Desired: 0,
    Number: "5",
    Of: "5",
    Dimension: "Data & Insights",
    Response_1: "My leaders don't prioritize fostering and monitoring change, leaving it mainly to HR.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Executives discuss change at a high level, but specialists handle it. No systemic approach to change exists.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our leaders prioritize change and foster organizational learning through openness and trust.  Busines leadership is synonymous with change leadership.",
  },
  {
    Description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    DiamondLoc: "rightCircle",
    Type: "Workforce Planning",
    Current: 0,
    Desired: 0,
    Number: "1",
    Of: "5",
    Dimension: "Strategy & Leadership",
    Response_1: "Our transformation projects are very ad hoc, and the business is not enagged or listened to.",
    Response_2: "My answer lies between 1 and 3",
    Response_3:
      "We are making progress, and while we attempt to listen to the business, it's not always clear which problems our  technology is solving.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our approach to transformation prioritizes understanding business problems using techniques such as design thinking to redesign experiences before implementing technology solutions.",
  },
  {
    DiamondLoc: "rightCircle",
    Type: "Workforce Planning",
    Current: 0,
    Desired: 0,
    Number: "2",
    Of: "5",
    Dimension: "Service | Program Design",
    Response_1: "Our innovation strategy lacks reliable data and modern tools and have no standard way of executing innovation.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Although we sporadically use data and toolsets, our problem-solving approach lacks consistency and a true scientific approach. ",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "We invest heavily in data, toolsets, training, and research to drive innovation using advanced technology.",
  },
  {
    DiamondLoc: "rightCircle",
    Type: "Workforce Planning",
    Current: 0,
    Desired: 0,
    Number: "3",
    Of: "5",
    Dimension: "Process",
    Response_1:
      "We are not encouraged to think creatively, as we are expected to adhere to our existing business model without much emphasis on innovation for new models.",
    Response_2: "My answer lies between 1 and 4",
    Response_3: "While we talk about the importance of innovation, we are not encouraged to take risks, and fear of failure holds us back.",
    Response_4: "My answer lies between 3 and 6",
    Response_5:
      "Our culture values experimentation and calculated risk-taking, supported by adherence to company wide methodologies. We have demonstrated success in generating new sources of growth.",
  },
  {
    DiamondLoc: "rightCircle",
    Type: "Workforce Planning",
    Current: 0,
    Desired: 0,
    Number: "4",
    Of: "5",
    Dimension: "Technology",
    Response_1: "Leaders prioritize results and current models, but neglect innovation despite recognizing its importance.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Leaders prioritize short-term results over innovation, lacking a clear plan or resources to foster it.",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "Leadership drives innovation with strategic planning, adaptability, and guidance.",
  },
  {
    DiamondLoc: "rightCircle",
    Type: "Workforce Planning",
    Current: 0,
    Desired: 0,
    Number: "5",
    Of: "5",
    Dimension: "Data & Insights",
    Response_1: "My leaders don't prioritize fostering and monitoring change, leaving it mainly to HR.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Executives discuss change at a high level, but specialists handle it. No systemic approach to change exists.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our leaders prioritize change and foster organizational learning through openness and trust.  Busines leadership is synonymous with change leadership.",
  },
  {
    Description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    DiamondLoc: "bottomCircle",
    Type: "Workforce Productivity",
    Current: 0,
    Desired: 0,
    Number: "1",
    Of: "5",
    Dimension: "Strategy & Leadership",
    Response_1: "Our transformation projects are very ad hoc, and the business is not enagged or listened to.",
    Response_2: "My answer lies between 1 and 3",
    Response_3:
      "We are making progress, and while we attempt to listen to the business, it's not always clear which problems our  technology is solving.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our approach to transformation prioritizes understanding business problems using techniques such as design thinking to redesign experiences before implementing technology solutions.",
  },
  {
    DiamondLoc: "bottomCircle",
    Type: "Workforce Productivity",
    Current: 0,
    Desired: 0,
    Number: "2",
    Of: "5",
    Dimension: "Service | Program Design",
    Response_1: "Our innovation strategy lacks reliable data and modern tools and have no standard way of executing innovation.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Although we sporadically use data and toolsets, our problem-solving approach lacks consistency and a true scientific approach. ",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "We invest heavily in data, toolsets, training, and research to drive innovation using advanced technology.",
  },
  {
    DiamondLoc: "bottomCircle",
    Type: "Workforce Productivity",
    Current: 0,
    Desired: 0,
    Number: "3",
    Of: "5",
    Dimension: "Process",
    Response_1:
      "We are not encouraged to think creatively, as we are expected to adhere to our existing business model without much emphasis on innovation for new models.",
    Response_2: "My answer lies between 1 and 4",
    Response_3: "While we talk about the importance of innovation, we are not encouraged to take risks, and fear of failure holds us back.",
    Response_4: "My answer lies between 3 and 6",
    Response_5:
      "Our culture values experimentation and calculated risk-taking, supported by adherence to company wide methodologies. We have demonstrated success in generating new sources of growth.",
  },
  {
    DiamondLoc: "bottomCircle",
    Type: "Workforce Productivity",
    Current: 0,
    Desired: 0,
    Number: "4",
    Of: "5",
    Dimension: "Technology",
    Response_1: "Leaders prioritize results and current models, but neglect innovation despite recognizing its importance.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Leaders prioritize short-term results over innovation, lacking a clear plan or resources to foster it.",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "Leadership drives innovation with strategic planning, adaptability, and guidance.",
  },
  {
    DiamondLoc: "bottomCircle",
    Type: "Workforce Productivity",
    Current: 0,
    Desired: 0,
    Number: "5",
    Of: "5",
    Dimension: "Data & Insights",
    Response_1: "My leaders don't prioritize fostering and monitoring change, leaving it mainly to HR.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Executives discuss change at a high level, but specialists handle it. No systemic approach to change exists.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our leaders prioritize change and foster organizational learning through openness and trust.  Busines leadership is synonymous with change leadership.",
  },
  {
    Description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    DiamondLoc: "leftCircle",
    Type: "Talent Acquisition",
    Current: 0,
    Desired: 0,
    Number: "1",
    Of: "5",
    Dimension: "Strategy & Leadership",
    Response_1: "Our transformation projects are very ad hoc, and the business is not enagged or listened to.",
    Response_2: "My answer lies between 1 and 3",
    Response_3:
      "We are making progress, and while we attempt to listen to the business, it's not always clear which problems our  technology is solving.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our approach to transformation prioritizes understanding business problems using techniques such as design thinking to redesign experiences before implementing technology solutions.",
  },
  {
    DiamondLoc: "leftCircle",
    Type: "Talent Acquisition",
    Current: 0,
    Desired: 0,
    Number: "2",
    Of: "5",
    Dimension: "Service | Program Design",
    Response_1: "Our innovation strategy lacks reliable data and modern tools and have no standard way of executing innovation.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Although we sporadically use data and toolsets, our problem-solving approach lacks consistency and a true scientific approach. ",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "We invest heavily in data, toolsets, training, and research to drive innovation using advanced technology.",
  },
  {
    DiamondLoc: "leftCircle",
    Type: "Talent Acquisition",
    Current: 0,
    Desired: 0,
    Number: "3",
    Of: "5",
    Dimension: "Process",
    Response_1:
      "We are not encouraged to think creatively, as we are expected to adhere to our existing business model without much emphasis on innovation for new models.",
    Response_2: "My answer lies between 1 and 4",
    Response_3: "While we talk about the importance of innovation, we are not encouraged to take risks, and fear of failure holds us back.",
    Response_4: "My answer lies between 3 and 6",
    Response_5:
      "Our culture values experimentation and calculated risk-taking, supported by adherence to company wide methodologies. We have demonstrated success in generating new sources of growth.",
  },
  {
    DiamondLoc: "leftCircle",
    Type: "Talent Acquisition",
    Current: 0,
    Desired: 0,
    Number: "4",
    Of: "5",
    Dimension: "Technology",
    Response_1: "Leaders prioritize results and current models, but neglect innovation despite recognizing its importance.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Leaders prioritize short-term results over innovation, lacking a clear plan or resources to foster it.",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "Leadership drives innovation with strategic planning, adaptability, and guidance.",
  },
  {
    DiamondLoc: "leftCircle",
    Type: "Talent Acquisition",
    Current: 0,
    Desired: 0,
    Number: "5",
    Of: "5",
    Dimension: "Data & Insights",
    Response_1: "My leaders don't prioritize fostering and monitoring change, leaving it mainly to HR.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Executives discuss change at a high level, but specialists handle it. No systemic approach to change exists.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our leaders prioritize change and foster organizational learning through openness and trust.  Busines leadership is synonymous with change leadership.",
  },
  {
    Description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    DiamondLoc: "middleCircle",
    Type: "Talent Management",
    Current: 0,
    Desired: 0,
    Number: "1",
    Of: "6",
    Dimension: "Strategy & Leadership",
    Response_1: "Our transformation projects are very ad hoc, and the business is not enagged or listened to.",
    Response_2: "My answer lies between 1 and 3",
    Response_3:
      "We are making progress, and while we attempt to listen to the business, it's not always clear which problems our  technology is solving.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our approach to transformation prioritizes understanding business problems using techniques such as design thinking to redesign experiences before implementing technology solutions.",
  },
  {
    DiamondLoc: "middleCircle",
    Type: "Talent Management",
    Current: 0,
    Desired: 0,
    Number: "2",
    Of: "6",
    Dimension: "Service | Program Design",
    Response_1: "Our innovation strategy lacks reliable data and modern tools and have no standard way of executing innovation.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Although we sporadically use data and toolsets, our problem-solving approach lacks consistency and a true scientific approach. ",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "We invest heavily in data, toolsets, training, and research to drive innovation using advanced technology.",
  },
  {
    DiamondLoc: "middleCircle",
    Type: "Talent Management",
    Current: 0,
    Desired: 0,
    Number: "3",
    Of: "6",
    Dimension: "Process",
    Response_1:
      "We are not encouraged to think creatively, as we are expected to adhere to our existing business model without much emphasis on innovation for new models.",
    Response_2: "My answer lies between 1 and 4",
    Response_3: "While we talk about the importance of innovation, we are not encouraged to take risks, and fear of failure holds us back.",
    Response_4: "My answer lies between 3 and 6",
    Response_5:
      "Our culture values experimentation and calculated risk-taking, supported by adherence to company wide methodologies. We have demonstrated success in generating new sources of growth.",
  },
  {
    DiamondLoc: "middleCircle",
    Type: "Talent Management",
    Current: 0,
    Desired: 0,
    Number: "4",
    Of: "6",
    Dimension: "Technology",
    Response_1: "Leaders prioritize results and current models, but neglect innovation despite recognizing its importance.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Leaders prioritize short-term results over innovation, lacking a clear plan or resources to foster it.",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "Leadership drives innovation with strategic planning, adaptability, and guidance.",
  },
  {
    DiamondLoc: "middleCircle",
    Type: "Talent Management",
    Current: 0,
    Desired: 0,
    Number: "5",
    Of: "6",
    Dimension: "Technology",
    Response_1: "Leaders prioritize results and current models, but neglect innovation despite recognizing its importance.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Leaders prioritize short-term results over innovation, lacking a clear plan or resources to foster it.",
    Response_4: "My answer lies between 3 and 5",
    Response_5: "Leadership drives innovation with strategic planning, adaptability, and guidance.",
  },
  {
    DiamondLoc: "middleCircle",
    Type: "Talent Management",
    Current: 0,
    Desired: 0,
    Number: "6",
    Of: "5",
    Dimension: "Data & Insights",
    Response_1: "My leaders don't prioritize fostering and monitoring change, leaving it mainly to HR.",
    Response_2: "My answer lies between 1 and 3",
    Response_3: "Executives discuss change at a high level, but specialists handle it. No systemic approach to change exists.",
    Response_4: "My answer lies between 3 and 5",
    Response_5:
      "Our leaders prioritize change and foster organizational learning through openness and trust.  Busines leadership is synonymous with change leadership.",
  },
];

const resultsList = [
  {
    type: "all",
    starting:
      "Starting organizations have no formal planning or strategy for their workforce development. They react to problems or requests as they arise, without considering the long-term implications or goals. They lack the tools, data, and skills to assess their current and future workforce needs. They often face challenges such as high turnover, low productivity, skill gaps, and poor alignment with organizational objectives.",
    developing:
      "Developing organizations have some basic planning and strategy for their workforce development, but they are not consistent or comprehensive. They use some tools, data, and skills to assess their current and future workforce needs, but they are not integrated or aligned. They face some challenges such as moderate turnover, average productivity, skill mismatches, and partial alignment with organizational objectives.",
    intermediate:
      "Intermediate organizations have a clear planning and strategy for their workforce development, but they are not fully implemented or optimized. They use various tools, data, and skills to assess their current and future workforce needs, but they are not fully integrated or aligned. They face few challenges such as low turnover, high productivity, skill matches, and strong alignment with organizational objectives.",
    advanced:
      "Advanced Organizations have a comprehensive planning and strategy for their workforce development, and they are fully implemented and optimized. They use sophisticated tools, data, and skills to assess their current and future workforce needs, and they are fully integrated and aligned. They face minimal challenges such as very low turnover, very high productivity, skill excellence, and optimal alignment with organizational objectives.",
  },
  {
    type: "workforce planning",
    starting:
      "Organizations with a starting level of workforce planning react to problems or requests as they arise, without considering the long-term implications or goals. They lack the tools, data, and skills to assess their current and future workforce needs. They often face challenges such as high turnover, low productivity, skill gaps, and poor alignment with organizational objectives. They need to improve their workforce maturity by implementing a systematic and proactive approach to workforce planning.",
    developing:
      "Developing organizations possess basic planning and strategy for their workforce development, but they are not consistent or comprehensive. They use some tools, data, and skills to assess their current and future workforce needs, but they are not integrated or aligned. They face challenges like moderate turnover, average productivity, skill mismatches, and partial alignment with organizational objectives. These organizations should implement a more systematic and proactive approach to workforce planning",
    intermediate:
      "Intermediate organizations have a clear planning and strategy for their workforce development, but they are not fully implemented or optimized. They use various tools, data, and skills to assess their current and future workforce needs, but they are not fully integrated or aligned. They face few challenges such as low turnover, high productivity, skill matches, and strong alignment with organizational objectives. They need to improve their workforce maturity by implementing a more advanced and proactive approach to workforce planning.",
    advanced:
      "Advanced organizations have a comprehensive planning and strategy for their workforce development, and they are fully implemented and optimized. They use sophisticated tools, data, and skills to assess their current and future workforce needs, and they are fully integrated and aligned. They face minimal challenges such as very low turnover, very high productivity, skill excellence, and optimal alignment with organizational objectives. They need to maintain their workforce maturity by implementing a continuous and proactive approach to workforce planning.",
  },
  {
    type: "extended workforce",
    starting:
      "Organizations with a starting level of MSP program maturity have no formal MSP program or strategy. They rely on external workers as a last resort, without considering the strategic benefits or risks. They lack the tools, data, and skills to manage and orchestrate their external workforce. They often face challenges such as compliance issues, quality problems, security breaches, and misalignment with organizational objectives. They need to improve their MSP program maturity by implementing a framework for orchestrating workforce ecosystems.",
    developing:
      "Developing organizations have some basic MSP program or strategy, but they are not consistent or comprehensive. They use external workers as a tactical solution, without considering the long-term implications or goals. They use some tools, data, and skills to manage and orchestrate their external workforce, but they are not integrated or aligned. They face some challenges such as legal and compliance considerations, integration architectures, performance management, and inclusion and engagement of external workers. They lack a systematic and proactive approach to Extended Workforce planning.",
    intermediate:
      "Intermediate organizations have a clear MSP program or strategy, but they are not fully implemented or optimized. They use external workers as a strategic lever, but they are not fully leveraging their potential or value. They use various tools, data, and skills to manage and orchestrate their external workforce, but they are not fully integrated or aligned. They face few challenges such as talent sourcing, workforce planning, collaboration and communication, and compensation and rewards. Diagnosing their Entended Workforce can lead to a more advanced and proactive approach to MSP program planning.",
    advanced:
      "Advanced organizations a comprehensive MSP program or strategy, and they are fully implemented and optimized. They use external workers as a competitive advantage, and they are fully harnessing their capabilities and contributions. They use sophisticated tools, data, and skills to manage and orchestrate their external workforce, and they are fully integrated and aligned. They face minimal challenges such as governance and risk management, innovation and learning, culture and diversity, and advocacy and sustainability. They need to maintain a continuous and proactive approach to MSP program planning.",
  },
  {
    type: "talent acquisition",
    starting:
      "Organizations with a starting level of talent acquisition maturity have no formal talent acquisition planning or strategy. They react to hiring needs as they arise, without considering the long-term implications or goals. They lack the tools, data, and skills to source, recruit, and hire the best talent for their organization. They often face challenges such as high turnover, low productivity, skill gaps, and poor alignment with organizational objectives. They need to improve their talent acquisition maturity by implementing a systematic and proactive approach to talent acquisition.",
    developing:
      "Developing organizations have some basic talent acquisition planning or strategy, but they are not consistent or comprehensive. They use talent acquisition as a tactical solution, without considering the strategic benefits or risks. They use some tools, data, and skills to source, recruit, and hire talent, but they are not integrated or aligned. They face some challenges such as legal and compliance considerations, integration architectures, performance management, and inclusion and engagement of talent. They need to improve their talent acquisition maturity by implementing a more systematic and proactive approach to talent acquisition.",
    intermediate:
      "Intermediate organizations have a clear talent acquisition planning or strategy, but they are not fully implemented or optimized. They use talent acquisition as a strategic lever, but they are not fully leveraging its potential or value. They use various tools, data, and skills to source, recruit, and hire talent, but they are not fully integrated or aligned. They face few challenges such as talent sourcing, workforce planning, collaboration and communication, and compensation and rewards. They need to improve their talent acquisition maturity by implementing a more advanced and proactive approach to talent acquisition.",
    advanced:
      "Advanced organizations have a comprehensive talent acquisition planning or strategy, and they are fully implemented and optimized. They use talent acquisition as a competitive advantage, and they are fully harnessing its capabilities and contributions. They use sophisticated tools, data, and skills to source, recruit, and hire talent, and they are fully integrated and aligned. They face minimal challenges such as governance and risk management, innovation and learning, culture and diversity, and advocacy and sustainability. They need to maintain their talent acquisition maturity by implementing a continuous and proactive approach to talent acquisition.",
  },
  {
    type: "talent management",
    starting:
      "Starting organizations have no formal talent management planning or strategy. They react to talent needs as they arise, without considering the long-term implications or goals. They lack the tools, data, and skills to develop, engage, and retain the best talent for their organization. They often face challenges such as high turnover, low productivity, skill gaps, and poor alignment with organizational objectives. They need to improve their talent management maturity by implementing a systematic and proactive approach to talent management.",
    developing:
      "Developing organizations have some basic talent management planning or strategy, but they are not consistent or comprehensive. They use talent management as a tactical solution, without considering the strategic benefits or risks. They use some tools, data, and skills to develop, engage, and retain talent, but they are not integrated or aligned. They face some challenges such as legal and compliance considerations, integration architectures, performance management, and inclusion and engagement of talent. They need to improve their talent management maturity by implementing a more systematic and proactive approach to talent management.",
    intermediate:
      "Intermediate organizations have a clear talent management planning or strategy, but they are not fully implemented or optimized. They use talent management as a strategic lever, but they are not fully leveraging its potential or value. They use various tools, data, and skills to develop, engage, and retain talent, but they are not fully integrated or aligned. They face few challenges such as talent sourcing, workforce planning, collaboration and communication, and compensation and rewards. They need to improve their talent management maturity by implementing a more advanced and proactive approach to talent management.",
    advanced:
      "Advanced organizations have a comprehensive talent management planning or strategy, and they are fully implemented and optimized. They use talent management as a competitive advantage, and they are fully harnessing its capabilities and contributions. They use sophisticated tools, data, and skills to develop, engage, and retain talent, and they are fully integrated and aligned. They face minimal challenges such as governance and risk management, innovation and learning, culture and diversity, and advocacy and sustainability. They need to maintain their talent management maturity by implementing a continuous and proactive approach to talent management .",
  },
  {
    type: "leadership & change",
    starting:
      "Starting organizations have no formal workforce strategy or leadership development plan. They react to workforce needs as they arise, without considering the long-term implications or goals. They lack the tools, data, and skills to align, engage, and empower their workforce. They often face challenges such as high turnover, low productivity, skill gaps, and poor alignment with organizational objectives. Employing transformational leadership can build a systematic and proactive approach to workforce development.",
    developing:
      "Developing organizationshave some basic workforce strategy or leadership development plan, but they are not consistent or comprehensive. They use workforce strategy and leadership development as a tactical solution, without considering the strategic benefits or risks. They use some tools, data, and skills to align, engage, and empower their workforce, but they are not integrated or aligned. They face some challenges such as legal and compliance considerations, integration architectures, performance management, and inclusion and engagement of workforce. Employing transformational leadership can help build a more systematic and proactive approach to workforce development.",
    intermediate:
      "Intermediate organizations have a clear workforce strategy or leadership development plan, but they are not fully implemented or optimized. They use workforce strategy and leadership development as a strategic lever, but they are not fully leveraging their potential or value. They use various tools, data, and skills to align, engage, and empower their workforce, but they are not fully integrated or aligned. They face few challenges such as talent sourcing, workforce planning, collaboration and communication, and compensation and rewards. Employing transformational leadership can build a more advanced and proactive approach to workforce development.",
    advanced:
      "Advanced organizations have a comprehensive workforce strategy or leadership development plan, and they are fully implemented and optimized. They use workforce strategy and leadership development as a competitive advantage, and they are fully harnessing their capabilities and contributions. They use sophisticated tools, data, and skills to align, engage, and empower their workforce, and they are fully integrated and aligned. They face minimal challenges such as governance and risk management, innovation and learning, culture and diversity, and advocacy and sustainability.",
  },
  {
    type: "workforce productivity",
    starting:
      "Starting organizations have no formal workforce productivity planning or strategy. They react to productivity issues as they arise, without considering the long-term implications or goals. They lack the tools, data, and skills to measure, improve, and sustain their workforce productivity. They often face challenges such as high turnover, low productivity, skill gaps, and poor alignment with organizational objectives. They need to improve their workforce productivity maturity by implementing a systematic and proactive approach to workforce development.",
    developing:
      "Developing organizations have some basic workforce productivity planning or strategy, but they are not consistent or comprehensive. They use workforce productivity as a tactical solution, without considering the strategic benefits or risks. They use some tools, data, and skills to measure, improve, and sustain their workforce productivity, but they are not integrated or aligned. They face some challenges such as legal and compliance considerations, integration architectures, performance management, and inclusion and engagement of workforce. They need to improve their workforce productivity maturity by implementing a more systematic and proactive approach to workforce development.",
    intermediate:
      "Intermediate organizations have a clear workforce productivity planning or strategy, but they are not fully implemented or optimized. They use workforce productivity as a strategic lever, but they are not fully leveraging its potential or value. They use various tools, data, and skills to measure, improve, and sustain their workforce productivity, but they are not fully integrated or aligned. They face few challenges such as talent sourcing, workforce planning, collaboration and communication, and compensation and rewards. They need to improve their workforce productivity maturity by implementing a more advanced and proactive approach to workforce development.",
    advanced:
      "Advanced organizations have a comprehensive workforce productivity planning or strategy, and they are fully implemented and optimized. They use workforce productivity as a competitive advantage, and they are fully harnessing its capabilities and contributions. They use sophisticated tools, data, and skills to measure, improve, and sustain their workforce productivity, and they are fully integrated and aligned. They face minimal challenges such as governance and risk management, innovation and learning, culture and diversity, and advocacy and sustainability . They need to maintain their workforce productivity maturity by implementing a continuous and proactive approach to workforce development.",
  },
  {
    type: "talent management",
    starting:
      "Starting organizations have no formal talent management planning or strategy. They react to talent needs as they arise, without considering the long-term implications or goals. They lack the tools, data, and skills to develop, engage, and retain the best talent for their organization. They often face challenges such as high turnover, low productivity, skill gaps, and poor alignment with organizational objectives. They need to improve their talent management maturity by implementing a systematic and proactive approach to talent management.",
    developing:
      "Developing organizations have some basic talent management planning or strategy, but they are not consistent or comprehensive. They use talent management as a tactical solution, without considering the strategic benefits or risks. They use some tools, data, and skills to develop, engage, and retain talent, but they are not integrated or aligned. They face some challenges such as legal and compliance considerations, integration architectures, performance management, and inclusion and engagement of talent. They need to improve their talent management maturity by implementing a more systematic and proactive approach to talent management.",
    intermediate:
      "Intermediate organizations have a clear talent management planning or strategy, but they are not fully implemented or optimized. They use talent management as a strategic lever, but they are not fully leveraging its potential or value. They use various tools, data, and skills to develop, engage, and retain talent, but they are not fully integrated or aligned. They face few challenges such as talent sourcing, workforce planning, collaboration and communication, and compensation and rewards. They need to improve their talent management maturity by implementing a more advanced and proactive approach to talent management.",
    advanced:
      "Advanced organizations have a comprehensive talent management planning or strategy, and they are fully implemented and optimized. They use talent management as a competitive advantage, and they are fully harnessing its capabilities and contributions. They use sophisticated tools, data, and skills to develop, engage, and retain talent, and they are fully integrated and aligned. They face minimal challenges such as governance and risk management, innovation and learning, culture and diversity, and advocacy and sustainability. They need to maintain their talent management maturity by implementing a continuous and proactive approach to talent management.",
  },
];

export { questionBank, resultsList, categoriesList };
