import BarVertical from "./BarVertical";

let MOCK_DATA = [
  {
    question: "Which of the following options best describes your current and desired maturity level of your HR technology ecosystem?",
    hs_formName: "q2",
    Type: "HR Ecosystem Maturity",
    Current: 2,
    Desired: 4,
    Number: 2,
    Of: 1,
    Dimension: "HR Ecosystem Maturity",
    Response_1: "Manual processes, isolated systems, minimal analytics, not aligned with strategy.",
    Response_2: "Some automation, partial system integration, basic analytics, initial alignment.",
    Response_3: "Mostly automated, good integration, regular analytics, aligned with strategy.",
    Response_4: "Fully integrated, advanced analytics and AI, real-time insights, fully strategic.",
    fieldType: "Slider Field",
    errorMessage: "Your desired level cannot be smaller than the current level.",
    selections: [],
    max: 0,
    other: "",
  },
  {
    question: "How would you rate the integration and use of skills in your HR processes and technology?",
    hs_formName: "q3",
    Type: "Skills Maturity",
    Current: 2,
    Desired: 4,
    Number: 3,
    Of: 1,
    Dimension: "Skills Maturity",
    Response_1: "Minimal skill integration; tech lacks tools for tracking or developing skills; low visibility.",
    Response_2: "Some skill consideration; limited tech features; occasional skill gap identification.",
    Response_3: "Skills integrated into key processes; robust tech features; proactive gap management.",
    Response_4: "Skills are a core focus; advanced tech and AI used; real-time data drives decisions.",
    fieldType: "Slider Field",
    errorMessage: "Your desired level cannot be smaller than the current level.",
    selections: [],
    max: 0,
    other: "",
  },
  {
    question: "What is your organization's readiness for these priorities?",
    hs_formName: "q5",
    Type: "HR Strategy and Planning",
    Current: 2,
    Desired: 3,
    Number: 5,
    Of: 1,
    Dimension: "HR Strategy and Planning",
    Response_1: "Some tools exist but lack standardization; basic metrics; starting alignment.",
    Response_2: "Standardized strategies; clear alignment; systematic metrics; cross-functional support.",
    Response_3: "Data-driven execution; continuous monitoring; aligned goals; high engagement.",
    Response_4: "Strategy embedded in culture; innovation; predictive analytics; strong agility.",
    fieldType: "Slider Field",
    errorMessage: "Your desired level cannot be smaller than the current level.",
    selections: [],
    max: 0,
    other: "",
  },
  {
    question: "How widely are the following HR technologies adopted and utilized by HR and business teams?",
    hs_formName: "q6",
    Type: "Implementation and Change Management",
    Current: 2,
    Desired: 3,
    Number: 6,
    Of: 3,
    Dimension: "Implementation and Change Management",
    Response_1: "Awareness and occasional use of HR technologies, minimal standardization, limited use, early benefits.",
    Response_2: "Comprehensive HR Technology solution implemented, standardized processes, regular use, improved integration.",
    Response_3: "Advanced tech fully integrated, strong data use, high adoption, strategic alignment.",
    Response_4: "HR Technologies embedded in culture, continuous innovation and optimization, real-time analytics, full business impact.",
    fieldType: "Slider Field",
    errorMessage: "Your desired level cannot be smaller than the current level.",
    selections: [],
    max: 0,
    other: "",
  },
  {
    question: "How would you rate your organization's capability to implement and manage these HR processes and technologies?",
    hs_formName: "q8",
    Type: "Implementation and Change Management",
    Current: 2,
    Desired: 4,
    Number: 9,
    Of: 3,
    Dimension: "Implementation and Change Management",
    Response_1: "Limited internal resources and expertise; significant external support needed.",
    Response_2: "Mix of internal resources and external support; some technologies managed internally.",
    Response_3: "Strong internal expertise; minimal external support needed for specialized tasks.",
    Response_4: "Robust internal resources; capable of independent implementation and management.",
    fieldType: "Slider Field",
    errorMessage: "Your desired level cannot be smaller than the current level.",
    selections: [],
    max: 0,
    other: "",
  },
  {
    question: "Is your organization currently leveraging artificial intelligence (AI) in its operations?",
    hs_formName: "q9",
    Type: "Digital HR Transformation",
    Current: 2,
    Desired: 3,
    Number: 10,
    Of: 3,
    Dimension: "Artificial Intelligence",
    Response_1: "AI is used in some pilot projects or isolated cases without major integration.",
    Response_2: "AI is systematically applied in several areas, with a structured integration approach.",
    Response_3: "AI is widely integrated into many processes; frameworks and governance are established.",
    Response_4: "AI is deeply embedded in culture and operations, driving innovation and agility.",
    fieldType: "Slider Field",
    errorMessage: "Your desired level cannot be smaller than the current level.",
    selections: [],
    max: 0,
    other: "",
  },
  {
    question: "How would you assess the maturity of the digital experience offered by your HR ecosystem?",
    hs_formName: "q10",
    Type: "Digital HR Transformation",
    Current: 2,
    Desired: 3,
    Number: 11,
    Of: 3,
    Dimension: "Digital Experience",
    Response_1: "HR systems are siloed, with no data sharing or integration; manual data entry is common.",
    Response_2: "Some systems are connected with limited data sharing; integration is basic and partly manual.",
    Response_3: "Most systems are integrated with automated data exchange; reliable data consistency.",
    Response_4: "All systems are fully integrated; real-time data updates and high data accuracy.",
    fieldType: "Slider Field",
    errorMessage: "Your desired level cannot be smaller than the current level.",
    selections: [],
    max: 0,
    other: "",
  },
  {
    question: "How do you assess the effectiveness of data utilization in HR decision-making within your organization?",
    hs_formName: "q11",
    Type: "Digital HR Transformation",
    Current: 2,
    Desired: 4,
    Number: 12,
    Of: 3,
    Dimension: "HR Data",
    Response_1: "Limited data collection; data rarely informs HR strategies or decisions.",
    Response_2: "Some decisions use basic data; data collected but not deeply analyzed.",
    Response_3: "Most decisions are data-supported; systematic data collection and analysis.",
    Response_4: "Data-driven decisions fully embedded; advanced analytics and predictive modeling widely used.",
    fieldType: "Slider Field",
    errorMessage: "Your desired level cannot be smaller than the current level.",
    selections: [],
    max: 0,
    other: "",
  },
];

function BarTest() {
  return (
    <div>
      <BarVertical data={MOCK_DATA} />
    </div>
  );
}

export default BarTest;
